### ISSUE TITLE
my nemesis > net-misc/ofono and net-libs/mbedtls dont like lto with gcc 9.1

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#294]
In file included from ell/random.c:34:
ell/missing.h:59:20: error: static declaration of 'explicit_bzero' follows non-static declaration
   59 | static inline void explicit_bzero(void *s, size_t n)
      |                    ^~~~~~~~~~~~~~
In file included from ./ell/util.h:26,
                 from ell/private.h:26,
                 from ell/random.c:33:
/usr/include/string.h:435:13: note: previous declaration of 'explicit_bzero' was here
  435 | extern void explicit_bzero (void *__s, size_t __n) __THROW __nonnull ((1));
      |             ^~~~~~~~~~~~~~
make[1]: *** [Makefile:3771: ell/random.lo] Error 1
make[1]: *** Waiting for unfinished jobs....

https://bugs.gentoo.org/show_bug.cgi?id=685184
idont know how to fix this ofono is broken 

UPDATE:::: COmpile fine with gcc-8.3.0 and with no -fipa-pta

**Comment by javashin** [comment]
AND 
net-libs/mbedtls-2.17.0::gentoo was built with the following:
USE="threads zlib -doc -havege -libressl -programs -static-libs -test" ABI_X86="32 (64) (-x32)" CPU_FLAGS_X86="sse2"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe"

Dont Compile with LTO anymore with gcc 9.1

**Comment by javashin** [comment]
Only compile like this

net-libs/mbedtls-2.17.0::gentoo was built with the following:
USE="threads zlib -doc -havege -libressl -programs -static-libs -test" ABI_X86="32 (64) (-x32)" CPU_FLAGS_X86="sse2"
CFLAGS="-O3 -march=native -mfpmath=both -fipa-pta -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -pipe -Wl,-O2 -Wl,--as-needed -fuse-ld=gold -Wl,--hash-style=gnu"
CXXFLAGS="-O3 -march=native -mfpmath=both -fipa-pta -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -pipe -Wl,-O2 -Wl,--as-needed -fuse-ld=gold -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -fuse-ld=gold -Wl,--hash-style=gnu"

**Comment by nivedita76** [comment]
Btw, note that loop-block and loop-strip-mine are aliases for loop-nest-optimize, and O3 turns on loop-interchange already.

From gcc/common.opt:
floop-strip-mine
Common Alias(floop-nest-optimize)
Enable loop nest transforms.  Same as -floop-nest-optimize.
floop-block
Common Alias(floop-nest-optimize)
Enable loop nest transforms.  Same as -floop-nest-optimize.

**Comment by javashin** [comment]
ok thanks @nivedita76
