### ISSUE TITLE
lto1: internal compiler error when building net-p2p/retroshare-0.6.4 

### ISSUE THREAD

**Issue by zeule** [InBetweenNames/gentooLTO#129]
lto1: internal compiler error: in get_odr_type, at ipa-devirt.c:2098

Probably an exception is needed.

**Comment by InBetweenNames** [comment]
Actually, I can't even get this to compile with GCC 8.1.0:

~~~
grouter/p3grouter.cc:543:65:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/include/g++-v8/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
~~~

**Comment by InBetweenNames** [comment]
I'm not sure which compiler you're using, but have you tried doing no-lto or fat-lto with it?

**Comment by InBetweenNames** [comment]
Oh great! Would you mind creating a PR to add `net-p2p/retroshare` as no-lto?

**Comment by zeule** [comment]
Please (#130).

**Comment by InBetweenNames** [comment]
Thanks for the contribution! :)
