### ISSUE TITLE
mail-client/mailx-8.1.2.20160123::gentoo fails with undefined reference to `strnvis'

### ISSUE THREAD

**Issue by amaury-d** [InBetweenNames/gentooLTO#482]
Hello

It is a known bug: https://bugs.gentoo.org/663516 in libbsd where compilation without lto fixes the situation.

**Comment by InBetweenNames** [comment]
Confirmed and fixed -- thank you!

**Comment by pchome** [comment]
FYI: https://gitlab.freedesktop.org/libbsd/libbsd/-/commit/c7a5d780ae58b6f7ae7d814fd5bc53cf1f58ee5f
> build: Allow building with -flto on gcc-10 and newer 

so probably should work with >=dev-libs/libbsd-0.11.4 compiled w/ LTO
