### ISSUE TITLE
sys-apps/pciutils and ncurses fail with LTO

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#111]
make[1]: Leaving directory '/var/tmp/portage/sys-apps/pciutils-3.5.6/work/pciutils-3.5.6-abi_x86_64.amd64/lib'
x86_64-pc-linux-gnu-gcc -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -pipe -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -floop-interchange -floop-strip-mine -floop-block -flto=36 -fuse-linker-plugin -ftree-vectorize  lspci.o ls-vpd.o ls-caps.o ls-caps-vendor.o ls-ecaps.o ls-kernel.o ls-tree.o ls-map.o common.o lib/libpci.so.3.5.6 -lkmod -o lspci                                                                                     
x86_64-pc-linux-gnu-gcc -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -pipe -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -floop-interchange -floop-strip-mine -floop-block -flto=36 -fuse-linker-plugin -ftree-vectorize  setpci.o common.o lib/libpci.so.3.5.6  -o setpci
x86_64-pc-linux-gnu-gcc -Wl,--as-needed -Wl,--hash-style=gnu -march=native -O3 -pipe -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -floop-interchange -floop-strip-mine -floop-block -flto=36 -fuse-linker-plugin -ftree-vectorize  example.o lib/libpci.so.3.5.6  -o example
/var/tmp/portage/sys-apps/pciutils-3.5.6/temp/ccJjTmuK.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0x506): undefined reference to `pci_filter_init'
<artificial>:(.text.startup+0x57d): undefined reference to `pci_filter_parse_slot'
<artificial>:(.text.startup+0xd6b): undefined reference to `pci_filter_match'
<artificial>:(.text.startup+0xdb8): undefined reference to `pci_filter_match'
<artificial>:(.text.startup+0xdf8): undefined reference to `pci_filter_parse_id'
collect2: error: ld returned 1 exit status
make: *** [Makefile:99: setpci] Error 1
make: *** Waiting for unfinished jobs....
/var/tmp/portage/sys-apps/pciutils-3.5.6/temp/ccbJlrzK.ltrans6.ltrans.o: In function `main':
<artificial>:(.text.startup+0x69): undefined reference to `pci_filter_init'
<artificial>:(.text.startup+0xdf): undefined reference to `pci_filter_parse_slot'
<artificial>:(.text.startup+0x15f): undefined reference to `pci_filter_parse_id'
/var/tmp/portage/sys-apps/pciutils-3.5.6/temp/ccbJlrzK.ltrans2.ltrans.o: In function `scan_device':
<artificial>:(.text+0x1af4): undefined reference to `pci_filter_match'
collect2: error: ld returned 1 exit status
make: *** [Makefile:99: lspci] Error 1

resolved by:

`sys-apps/pciutils *FLAGS-=-flto*`

**Comment by wolfwood** [comment]
ah, I think it was a problem with gcc 6.4.0
just worked on 7.3.0-r1

**Comment by wolfwood** [comment]
while I'm here, is there a reason not to put -fuse-linker-plugin in LTO? I've had do sys-libs/ncurses *FLAGS-=-flto* *FLAGS=-fuse-linker-plugin with gcc 7.3.0, worked on 6.4.0.

**Comment by wolfwood** [comment]
ncurses build log [Uploading build.log…]()

**Comment by InBetweenNames** [comment]
No worries! It's good you made an issue about this because now other users can find this too. The reason that we only turn off `-flto` is that by itself `-fuse-linker-plugin` doesn't do anything, and in fact users could have other linker plugins as well which we don't want to interfere with. Is the problem solved for you now?

**Comment by wolfwood** [comment]
fails with ld.bfd as well, when only -fuse-linker-plugin is enabled

**Comment by InBetweenNames** [comment]
Yeah I use `ld.gold` as well as much as possible. Really helps with the compile times. Looking at this log, you're actually getting a segfault during the install phase when it's trying to generate terminfo. Weird. Could you post a complete build.log for your pciutils too?

**Comment by wolfwood** [comment]
succeeds with gcc 7.3.0, but here is the 6.4.0 failure
[pciutils-gcc6.4.0-build.log](https://github.com/InBetweenNames/gentooLTO/files/1971676/pciutils-gcc6.4.0-build.log)

**Comment by wolfwood** [comment]
I'm also getting an LTO ICE with python 3.5/3.6 pgo in gcc 7.3.0. build succeeds with gcc 6.4.0, and build succeeds with pgo off on gcc 7.3.0. python 2.7 is good in all cases.

[python3.6-gcc7.3.0-build.log](https://github.com/InBetweenNames/gentooLTO/files/1971703/python3.6-gcc7.3.0-build.log)

**Comment by InBetweenNames** [comment]
I just rebuilt Python 3.6 with O3, Graphite, LTO and PGO using GCC 8.1.0 without any issues. Would you be willing to upgrade to GCC 8.1.0 to try it out?

I have managed to reproduce your ncurses problem however. The solution was actually removing `-Wl,--as-needed` from `*FLAGS`. This prevented `libdl` from being linked against due to how `LDFLAGS` are handled internally to the package. I'll push a commit shortly to address this. I have confirmed both versions 5 and 6 work using this approach.

**Comment by wolfwood** [comment]
I am willing, if you can supply an ebuild. if it works we should talk about parallelizing the profiling test execution :)

**Comment by InBetweenNames** [comment]
I was just thinking about that today! I didn't even realize it was running sequentially. Actually, an ebuild should be available for you in the Gentoo main portage tree, you'll just have to add it to your `package.accept_keywords`. Worked perfectly for me on the first try.

**Comment by wolfwood** [comment]
there is nothing in /usr/portage/sys-devel/gcc/ beyond gcc-7.3.0-r2 for me, maybe it came from an overlay?

gonna spend a few hours rebuilding world with gcc-7.3.0 just to make sure I've caught all the issues, before upgrading.

**Comment by InBetweenNames** [comment]
I just realized, I'm on the git version of the Gentoo portage, so you probably won't find it in your tree just yet. You can find the ebuild here: https://github.com/gentoo-mirror/gentoo/tree/stable/sys-devel/gcc

Good call on rebuilding world first -- I'm scheduled for a rebuild today as well since I just upgraded to GCC 8.1.0. So far it's looking very good.

**Comment by wolfwood** [comment]
rebuilding world with gcc 7.3 worked except for a configuration issue with firefox. does 59.0.02 work for you?
[firefox59.0.2-build.log](https://github.com/InBetweenNames/gentooLTO/files/1972739/firefox59.0.2-build.log)

**Comment by wolfwood** [comment]
gcc 8 hit rsync
rebuilding @system with gcc 8.1.0, seeing nasm failures, which seem to be a change in the enforcement of -Werror=attributes

./include/nasmlib.h:194:1: error: ‘pure’ attribute on function returning ‘void’ [-Werror=attributes]
 void pure_func seg_init(void);
[nasm2.13.01-gcc8.1.0-build.log](https://github.com/InBetweenNames/gentooLTO/files/1972925/nasm2.13.01-gcc8.1.0-build.log)

to be fair, gcc is right, a truly pure void function would be a no-op.

**Comment by wolfwood** [comment]
gcc-8 did fix the python lto+pgo issue I was hitting, currently rebuilding `@world`

can't fix the nasm issue with -Wno-error=attributes because CFLAGS go before the flags it is adding to trigger the failure, which then override.

**Comment by InBetweenNames** [comment]
Yeah I've noticed a bunch of non-LTO-overlay related issues today as I rebuilt `@world`, including what you have seen with nasm. I've elected to just skip over any packages which wouldn't compile due to those issues. So far I think there's about 10 to 15 I've run into, so I'm not too worried.

Regarding Firefox, I'm actually on `60.0_beta14` which seems to work as it did before. After my world rebuild I'm going to try to give it the LTO treatment once again.

**Comment by wolfwood** [comment]
dev-cpp/atkmm
dev-cpp/glibmm
dev-cpp/pangomm
dev-cpp/gtkmm
media-sound/pavucontrol

all fail, seems like a related 'passing a GObject in place of a GOject*` issue.

nasm and firefox still fail.

everything else succeeded.

**Comment by InBetweenNames** [comment]
Yup that mirrors my experience. I'm guessing that something in GLib is playing fast and loose with the implicit conversion rules. It may be possible to patch the nasm ebuild to allow it to build with 8.1.0 by patching the build system. Actually, what do you think about creating a separate issue to track packages that don't build with 8.1.0? Could be helpful to others who are doing the same as us.

**Comment by wolfwood** [comment]
looks like nasm and also a freetype issue got fixed overnight.

gcc 8.1.0 GObject issue makes sense to me if you like for convenience, but we can link to https://bugs.gentoo.org/654776
 https://bugs.gentoo.org/654772 etc. which seem to have a working patch already.

firefox-59.0.2 still borked

pciutils and ncurses both seem to be fixed with gcc so the original intent of this issue is resolved (and I have no additional packages.cflags set)

so the only 'actionable' item would be a new issue for python pgo parallelization

**Comment by wolfwood** [comment]
I dropped the patch from https://bugs.gentoo.org/654776 in /etc/portage/patches/dev-cpp/glibmm and now the pavucontrol and C++ bindings to glib are all happy, so I expect that use will be resolved soon.

**Comment by InBetweenNames** [comment]
Excellent. Why don't you kick off the discussion w.r.t Python PGO parallelization in a new issue? I'll close this one as it seems everything is resolved just to keep things tidy.
