### ISSUE TITLE
media-libs/dav1d doesn't compile with LTO

### ISSUE THREAD

**Issue by lovesegfault** [InBetweenNames/gentooLTO#241]
It'd be nice if someone else could verify this before I make a PR with the fix. @InBetweenNames Any chance you can test this?

**Comment by pchome** [comment]
```c
:<artificial>:function dav1d_decode_frame: error: undefined reference to '__wrap_malloc'
```
:man_shrugging: 

```diff
--- dav1d-0.1.0.ebuild
+++ dav1d-0.1.0.ebuild
@@ -19,7 +19,7 @@
 
 LICENSE="BSD-2"
 SLOT="0"
-IUSE="+8bit +10bit +asm"
+IUSE="+8bit +10bit +asm tests tools"
 
 ASM_DEPEND=">=dev-lang/nasm-2.13"
 RDEPEND=""
@@ -45,6 +45,8 @@
        local emesonargs=(
                -D bitdepths=$(IFS=,; echo "${bits[*]}")
                -D build_asm=$build_asm
+               $(meson_use tests build_tests)
+               $(meson_use tools build_tools)
        )
        meson_src_configure
 }
```
`# USE="-tests tools" emerge -1B media-libs/dav1d -q` - ok.

**Comment by InBetweenNames** [comment]
Seems to be working on my system.  Can anyone reproduce this?

**Comment by bemeurer** [comment]
Seems to work here as well, can't reproduce anymore. Cheers!

**Comment by InBetweenNames** [comment]
Closing as it has been confirmed working on GCC 8.2.0 and GCC 8.3.0.
