### ISSUE TITLE
sys-boot/grub doesn't recognize sys-fs/fuse when built with LTO under GCC 8.2

### ISSUE THREAD

**Issue by gcs-github** [InBetweenNames/gentooLTO#139]
GCC 8.2.0
binutils 2.30-r3
sys-fs/fuse-2.9.7-r1
sys-boot/grub-2.02-r2

* sys-boot/grub depends on sys-fs/fuse when built with the `mount` USE flag.
* if fuse is built with LTO with GCC 8.1, grub builds successfully
* if fuse is built without LTO with GCC 8.2, grub builds successfully
* if fuse is built with LTO with GCC 8.2, grub's `src_configure` crashes with the following:

```
checking for fuse_main_real in -lfuse... no
configure: error: grub-mount was explicitly requested but can't be compiled (need FUSE library)
```

In that case, grub's config.log mentions the following:

```
configure:27875: x86_64-pc-linux-gnu-gcc -o conftest   -D_FILE_OFFSET_BITS=64  conftest.c -lfuse   >&5
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libfuse.so: undefined reference to `__fuse_read_cmd'
```

implying that libfuse.so might be linked incorrectly.

Enforcing `*FLAGS-=-flto*` on sys-fs/fuse solves the build issue.

**Comment by InBetweenNames** [comment]
Just curious, did you do a full system rebuild with 8.2.0?

**Comment by gcs-github** [comment]
Yes. Ran `emerge -ve1 @system @world` as soon as I switched compilers.

**Comment by InBetweenNames** [comment]
I actually have not been able to reproduce this.  I have `sys-boot/grub` with `USE=mount` enabled with `sys-fs/fuse` and `sys-boot/grub` both enabled with LTO.  Is the issue still affecting you?  Also, what is your binutils version and linker?

**Comment by gcs-github** [comment]
Still occurring after fixing my CXXFLAGS to be equal to my CFLAGS and rebuilding the entire system.

Updated my `emerge --info` comment above with the updated result

**Comment by InBetweenNames** [comment]
Thanks for the detailed post!

This line sticks out to me:
~~~
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -O3 -pipe -march=haswell -flto=8 -fuse-linker-plugin -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize"
~~~

I've actually never heard of `-Wl,-O1` until now, and I just looked it up -- it appears to optimize the final shared object library size.  I'm curious if you take this out of your `LDFLAGS` if it changes anything (rebuilding `sys-fs/fuse` and then `sys-boot/grub` in order).

Otherwise, your setup looks great!  The next thing I'll try to do is replicate your exact flags here for those two packages and see if I can reproduce the error, if the above approach doesn't work.

**Comment by gcs-github** [comment]
Thanks!

I tried what you recommended, without success. I event tried removing everything from my `LDFLAGS` in a second run just to be sure.

The presence or absence of `-flto=8` in my `CFLAGS` for the compilation of `sys-fs/fuse-2.9.7-r1` seem to be making the difference alone for me.

My `emerge -pv` output for fuse and grub both, in case you want to try and match me USE flag for USE flag:
```
[ebuild   R    ] sys-fs/fuse-2.9.7-r1::gentoo  USE="-examples -static-libs" 0 KiB
[ebuild   R    ] sys-boot/grub-2.02-r2:2/2.02-r2::gentoo  USE="device-mapper fonts libzfs mount nls themes -debug -doc -efiemu -multislot -sdl -static (-test) -truetype" GRUB_PLATFORMS="efi-64 pc qemu -coreboot -efi-32 -emu -ieee1275 -loongson -multiboot -qemu-mips -uboot -xen -xen-32" 0 KiB
```

**Comment by gcs-github** [comment]
Looking further, I found this Gentoo bug reporting the same missing symbol with libfuse.so when built with LTO: https://bugs.gentoo.org/663518

**Comment by gcs-github** [comment]
And of course, same symbol in libfuse.so at stake in issue #142

**Comment by gcs-github** [comment]
I'm able to get over the problem in `libfuse.so` by switching the linker to `ld.gold`, however, `grub` with `libzfs` enabled doesn't seem to play well with `ld.gold`, while `ld.bfd` causes no problem in that case.

Trading one problem for another. :)

Are you using `ld.gold` @InBetweenNames ? If you do, that might explain why you couldn't reproduce this problem and others related to libfuse.

**Comment by gcs-github** [comment]
One thing with `ld.gold` however: `nm` reports that the `__fuse_read_cmd` is still undefined in `libfuse.so` in that case as well. The difference is that grub's `src_configure` doesn't crash because of it anymore, for some reason.

**Comment by InBetweenNames** [comment]
I am indeed using `ld.gold`! Good catch.  I just tested out `sys-boot/grub` with `USE=libzfs mount` and it seemed to emerge fine using `ld.gold`.  This is very interesting.  Checking the `config.log`:
~~~
configure:27850: checking for fuse_main_real in -lfuse
configure:27875: x86_64-pc-linux-gnu-gcc -o conftest   -D_FILE_OFFSET_BITS=64  conftest.c -lfuse   >&5
configure:27875: $? = 0
~~~

I'm glad this has been reported upstream too.  I think the best option for fuse right now is to leave it as no-lto, and once those issues get sorted out we'll bring it back.

**Comment by InBetweenNames** [comment]
By all accounts, it shouldn't be working.  The only thing I can think of is this:
https://github.com/osxfuse/fuse/blob/master/include/fuse.h#L1116

~~~
# define __fuse_read_cmd fuse_read_cmd
~~~

It seems to be a compatibility thing.  And it also seems that `__fuse_read_cmd` is supposed to be an unversioned symbol that maps directly to the real `fuse_read_cmd`.  For some reason in the LTO build, that mapping is left undefined and we get a symbol resolution error.

Only other thing I can think of is that I'm using binutils 2.31.1.

**Comment by gcs-github** [comment]
We're both on binutils 2.31.1 now.

If we go back to my original report, this could very well be a regression in GCC. Compiling the same fuse ebuild with GCC 8.1.0 with LTO seemed to work.

**Comment by InBetweenNames** [comment]
Indeed.  One more tidbit, found at:
https://github.com/libfuse/libfuse/blob/fuse_2_9_bugfix/lib/fuse.c#L4953

~~~
FUSE_SYMVER(".symver fuse_read_cmd,__fuse_read_cmd@");
~~~

Notably, this symbol is completely absent in fuse 3.x.  Probably why it's masked.

I went ahead and followed the breadcrumbs:
https://github.com/libfuse/libfuse/commit/918f0ad95b73e506d20488cb8ddd35d1a2524c7c
https://github.com/libfuse/libfuse/commit/f458b8c07b521cfb48152e5d3344cd22989aa4ab
https://github.com/libfuse/libfuse/commit/0b6a0adc4d44e5b9d0855e257091eec643f3a185

These seem to indicate these are in for backwards compatibility.  For some reason, under LTO, these are being omitted.

Most recent documentation on symver is here:
https://sourceware.org/binutils/docs-2.31/as/Symver.html#Symver

**Comment by gentoo-cba** [comment]
I found you through this error. I have been running my own lto overlay for the last 3 years ;) 
Using O3 all the time is a ricer CFLAG btw. I'll stick with what I've got.
It started with https://wiki.ixit.cz/lto but now it's very much my own and very different package.env / env configuration.

**Comment by gentoo-cba** [comment]
https://funroll-loops.teurasporsaat.org/ It looks like the queers at systemd really hate us for http://without-systemd.org/wiki/index.php/Boycottsystemd.org / elogind......

**Comment by gentoo-cba** [comment]
I just compiled grub with my graphite/lto etc overlay and gcc 8.2.0.... Install size 40megs from portage. With gcc-4.4.7 it's 35megs. Doesn't a smaller code size iterate faster when you factor in cache utilization?  Having a code size that is 5 megs bigger runs faster? grub should be compiled with gcc 4.4 - read the ebuild einfo messages it pumps out anyway - so why is the OP here actually trying to compile grub with LTO and GCC 8.2.0 unless he want's his runtime failures to happen faster?

**Comment by InBetweenNames** [comment]
@gentoo-cba , please refer to the `CODE_OF_CONDUCT.md` in this repo.  It's available here:

https://github.com/InBetweenNames/gentooLTO/blob/master/CODE_OF_CONDUCT.md

Comments such as "It looks like the queers at systemd really hate us" are not welcome here.

No one's telling you that you need to be running `-O3` all the time.  In fact, running your own flags is supported by using `make.conf.lto.defines` directly, as shown in `README.md`.  That said, `-O3` has been shown consistently to produce better code compared to `-O2`, especially on newer GCCs.  Binary size isn't everything.  If it were, `-O3` would be just an alias for `-Os`.  If you really want to prove a point though, feel free to participate in issue #123.  We could really use more benchmarks.  Currently, we're using a subset of the flags Clear Linux uses, which have been shown to consistently outperform the `-O2` defaults.

Based on the survey that was started a couple weeks ago, most users are using `-O3` system wide just fine.  Doing a `git blame` on `sys-boot/grub` yields this:

https://github.com/gentoo/gentoo/blame/master/sys-boot/grub/grub-2.02-r3.ebuild

Note this commit:

https://github.com/gentoo/gentoo/commit/bab479f78d08aaab25917e51f90b85e0ca5f42b4

There's nothing special about GCC 4.4.

**Comment by gentoo-cba** [comment]
You meen the code of conduct made by a transgender gay dad member of the OTO child sex cult that mandates chlidren join the gnostic catholic mass child orgy ritual @CoralineAda exposed here (warning with photos to prove the code of conduct you speak of made by a pedophlie).
https://153news.net/watch_video.php?v=8913 
http://archive.is/adyMm
https://www.youtube.com/watch?v=YENV04YmDVQ

Eek enough said - I'm out of here. Your social justice policy says we must respect **all sexual preferences** clearly - and the left clearly says in the video above YOU MUST ACCEPT CHILD SEX LOVERS PEDOS AS A SEXUAL PREFERENCE NOT A MENTAL ILNESS like the DSM-III said homosexuality was. Your policy says I must repsect pedophiles and you can't force me to love sex with children.

Then you idiots try and use creator commons to say we own the copyright to videos of us saying sex with children is a sexual preference - feel sorry for the child sex lovers....

https://www.breitbart.com/tech/2018/06/22/ted-talk-organization-under-fire-for-bizarre-pedophilia-lecture/

So therefore according to ted talks - creative commons means you can share / reuse stuff - unless it exposes us loving sex with children - in which case it's ILLEGAL - SHUT IT DOWN! TO EXPOSE THOSE WHO LOVE SEX WITH CHILDREN IS "ILLEGAL" OH VEY SHUT IT DOWN!

https://www.vice.com/en_ca/article/qbe8bp/the-child-rape-assembly-line-0000141-v20n11

The founder of the creator covenent (gay dads transgender who campaigns for "women's rights)  tweets an image about giving his son squishy bum stress toy. If I was bad as him I'd give my daughter a dildo at age 4 - and I'm not going to do that because I'm not a sick pedo like the guy who made the creator covenant you directed me to that says love sex with children. 

To quote the Ebuild - THE OP is wrong - You SHOULD NOT build grub with gcc-8.2.0 - extreme ricer activity - and that's coming from a gentoo user since  2001.

(35 megs with gcc-4.2 as advised).
```
 * Final size of installed tree:   41564 KiB ( 40.5 MiB)


>>> Installing (1 of 1) sys-boot/grub-9999::user_defined
 * For information on how to configure GRUB2 please refer to the guide:
 *     https://wiki.gentoo.org/wiki/GRUB2_Quick_Start

 * Messages for package sys-boot/grub-9999:

 * Forcing usage of the BFD linker instead of GOLD
 * 
 * Entropy administration information:
 * 
 * ~~~   READ THIS CAREFULLY   ~~~
 * if you are bumping sys-boot/grub:0
 * please MAKE SURE to compile it with gcc-4.4.
 * Later GCC versions could cause runtime failures
 * ~~~   READ THIS CAREFULLY   ~~~
 * 
 * For information on how to configure GRUB2 please refer to the guide:
 *     https://wiki.gentoo.org/wiki/GRUB2_Quick_Start
>>> Auto-cleaning packages...
```

**Comment by gentoo-cba** [comment]
Oh I worked with a wasington times reporter Robert Stacy McCain of #FreeStacy #1 trending hashtag in the USA to protest twitter censorship fame to write up the story above... yes.. Even Eric S Raymond the OTO occultist pedo fan got in on the comments.

http://theothermccain.com/2018/05/30/coraline-ada-ehmke-transgender-feminist-satanic-sjw/

You can see a video of the creator of the creator coveneant says I'm great in his keynote speak because I only tried to kill myself twice last year - another bradley manning fake suacide attention seeking virtual signalling. 

https://www.counterpunch.org/2016/02/24/freestacy-twitter-meets-the-sarkeesian-method-and-the-streisand-effe

Now you know why his twitter avatar is a pyramid.

**Comment by gentoo-cba** [comment]
You could have been nice and I could have given you my /etc/portage/env /etc/portage/profile.env etc for comparision but no - you push that pedo's policy at me..... Like I said I'm out of here.... And O2 is faster unless you have a Xenon with a friggen massive cache.
I use O3 on decoding videos and other most intenstive operations - but for the bulk of the other stuff you want the code size small. O2 with graphite / lto is what I use by default.

**Comment by InBetweenNames** [comment]
OOOoookay... well, that escalated quickly.  I'm going to have to remove these posts for being incredibly insensitive and not contributing anything worthwhile to the discussion.

Regarding this:

~~~
 * ~~~   READ THIS CAREFULLY   ~~~
 * if you are bumping sys-boot/grub:0
 * please MAKE SURE to compile it with gcc-4.4.
 * Later GCC versions could cause runtime failures
 * ~~~   READ THIS CAREFULLY   ~~~
~~~

I can't even find this text in `/usr/portage`.  Given this is from an overlay, `user_defined`, I have to assume this isn't the official `sys-boot/grub` you're referencing.  Which is fine, but that also means this comment means nothing, since it's unqualified.  Without references, or a bug report upstream, why should anyone take it at face value?

As for your own Portage configuration, I think we're good.  If you want to contribute them, you can email me directly.  In the meantime, I will be removing your posts and if I can, I will prevent you from posting here further.

**Comment by gentoo-cba** [comment]
The only thing I changed was a patch for grub and crypto.

**Comment by gentoo-cba** [comment]
http://archive.is/dbEB1 Censorship will get you nowhere.
Pro pedophile censorship is everywhere.

**Comment by gentoo-cba** [comment]
I'll build it again without a user defined repo - standby....

**Comment by InBetweenNames** [comment]
@gentoo-cba , if you want to discuss the code of conduct you can email me directly.  This isn't the place for that.  I have left up the non-abusive comments you've made.

**Comment by InBetweenNames** [comment]
Well, I'm glad that's over with.  Going to leave the issue open for hopefully more constructive discussion.
